var fruits = ["apple", "banana"];
fruits.push("cherry");
console.log("Fruits array ".concat(fruits));
var arrayNum = [1, 2];
arrayNum.push(3);
arrayNum.push(4);
console.log("Number array length : ", arrayNum.length);
console.log("Number array :" + arrayNum);
var colors = [];
colors.push("red");
colors.push("green");
colors.push("blue");
console.log("Colors array: ".concat(colors));
var numArr2 = [10, 20, 30, 40];
numArr2.pop();
console.log("After using pop() first time ".concat(numArr2));
numArr2.pop();
console.log("After using pop() second time ".concat(numArr2));
var numArr3 = [5, 10];
numArr3.push(15);
numArr3.pop();
numArr3.push(20);
console.log("Number Array 3 ".concat(numArr3));
