var alphabets = ["a", "b", "c"];
alphabets.shift();
console.log("After shifting : ".concat(alphabets));
var arr1 = [10, 20];
arr1.unshift(5);
arr1.shift();
console.log("Number Array 1 : ".concat(arr1));
var mixArray = [1, 2, 3];
mixArray.unshift("x", "y");
console.log("Mixed Array after unshifting x and y is ".concat(mixArray));
